
FAIL event.intercept() should abort if the given promise rejects assert_equals: expected "#1" but got ""

